title = "Oscar Wei"
baseURL = "https://example.com/"
theme = "hugo-resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

[params]
address = "Austin,Texas"
email = "Oscarwei@utexas.edu"
favicon = "/favicon.ico"
firstName = "Oscar"
lastName = "Wei"
phone = "512-922-1323"
profileImage = "img/Oscar-wei.png"
showEducation = true
showExperience = true
showOpenSource = true
showProjects = true
showPublications = true
showQr = false
showSkills = true

[params.google]

[params.google.analytics]
trackerID = "XX-123446-01"

[[params.handles]]
link = "https://www.linkedin.com/in/junyu-wei-987584223/"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/junyu02"
name = "GitHub"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"